# Site settings
title: LEE-HYUN-JE
description: "Backend Engineer | Technical Blog"
baseurl: ""
url: "https://lee-hyun-je.github.io"

# excerpt(미리보기) 기준
excerpt_separator: "<!--more-->"

# 고정 태그 목록 (탭에 노출)
portfolio_tags:
  - Devops
  - Backend
  - Etc
  - ComputerScience
  - AWS
  - Secure

# Author
author:
  name: Hyunje Lee
  email: your-email@example.com
  github: LEE-HYUN-JE

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Pagination
paginate: 6
paginate_path: "/posts/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Hyunje Lee"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
